import type { Metadata } from "next";

import type { ServiceContent } from "@/types/service-content";

export interface PageMetadataInput {
  readonly title: string;
  readonly description: string;
  /** Root-relative path, e.g. "/contact-us". */
  readonly path: string;
}

/*
 * A page-level `openGraph` replaces the one in the root layout rather than
 * merging with it, so the share card generated by `app/opengraph-image.tsx`
 * has to be named on every page or only the home page gets a picture.
 */
const shareImage = {
  url: "/opengraph-image",
  width: 1200,
  height: 630,
} as const;

/**
 * Builds the per-page metadata. Every page needs its own title, description and
 * canonical: the previous build served one shared title across all ten URLs.
 */
export function buildPageMetadata({
  title,
  description,
  path,
}: PageMetadataInput): Metadata {
  return {
    title,
    description,
    alternates: { canonical: path },
    openGraph: {
      title,
      description,
      url: path,
      type: "website",
      images: [shareImage],
    },
  };
}

export function buildServiceMetadata(service: ServiceContent): Metadata {
  return buildPageMetadata({
    title: service.metaTitle,
    description: service.metaDescription,
    path: `/${service.slug}`,
  });
}
